mocktest/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if(current_user.is_authenticated):
        return render_template('base.html', image_file=current_user.image_file)
    else:
        return render_template('base.html')

mocktest/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, Markup, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from mocktest import db, bcrypt
from mocktest.models import User, Marks
from mocktest.users.forms import (RegistrationForm, LoginForm, AccountUpdateForm,
                                   RequestResetForm, ResetPasswordForm)
from mocktest.users.utils import save_picture,send_reset_email
# from sqlalchemy import desc


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        if form.gender.data == 'Male':
            image_file = 'male.png'
        elif form.gender.data == 'Female':
            image_file = 'female.png'
        else :
            image_file = 'other.png'
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, gender=form.gender.data, image_file=image_file)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to login', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(Markup(f'Login Successful! Welcome <strong>{ current_user.username }</strong>'), 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = AccountUpdateForm()
    if form.validate_on_submit():
        if form.username.data:
            current_user.username = form.username.data
        if form.picture.data:
            picture_file, picture_success = save_picture(form.picture.data)     
            if picture_success:
                current_user.image_file = picture_file
            else:
                flash('Error while updating profile picture', 'danger')   
        if form.address.data:
            current_user.address = form.address.data
        if form.phoneno.data:
            current_user.phoneno = form.phoneno.data
        db.session.commit()
        flash('Your account was successfully updated!', 'success')  
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        if not current_user.phoneno=='None':
            form.phoneno.data = current_user.phoneno
        if not current_user.address=='None':
            form.address.data = current_user.address
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file = image_file, form=form)

@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password (Check spam folder too).','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an expired or invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route("/performance", methods=['GET'])
@login_required
def performance():
   
    temp_java_marks = Marks.query.filter_by(subject='java-question', user_id=current_user.id).order_by(Marks.attempted_on.desc()).limit(10)
    temp_python_marks = Marks.query.filter_by(subject='python-question', user_id=current_user.id).order_by(Marks.attempted_on.desc()).limit(10)

    java_marks = [java_mark.to_dict(only=('id','subject','module','marks_obtained','attempted_on')) for java_mark in temp_java_marks]
    python_marks = [python_mark.to_dict(only=('id','subject','module','marks_obtained','attempted_on')) for python_mark in temp_python_marks]

    java_result = java_marks[::-1]
    python_result = python_marks[::-1]

    return render_template('performance.html', title=current_user.username+"'s Performance", image_file=current_user.image_file,
     java_marks=java_result, python_marks=python_result)

mocktest/templates/account.html
{% extends "base.html" %}

{% block header %}
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top mb-3">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Web Academy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('tests.java') }}">Java</a>
              <a class="nav-item nav-link" href="{{ url_for('tests.python') }}">Python</a>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle ml-3" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 0px;">
                  {% if current_user.image_file=='default.png' %}
                    {% if current_user.gender=='Male'%}
                      <img class="rounded-circle" style="width:40px ;height:40px;" src="../static/profile_pics/male.png">
                    {% elif current_user.gender=='Female'%}
                      <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/female.png">
                    {% else %}
                      <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/other.png">
                    {% endif %}
                  {% else %}
                    <img class="rounded-circle" style="width:40px ;height:40px" src="{{ image_file }}">
                  {% endif %}
                </a>
                <div class="dropdown-menu mt-2" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('users.account') }}" style="font-weight: 500;"><i class="bi bi-person-lines-fill pr-2"></i>Account</a>
                  <a class="dropdown-item" href="{{ url_for('users.performance') }}"><i class="bi bi-graph-up pr-2"></i>Performance</a>
                  <a class="dropdown-item bg-danger text-white" href="{{ url_for('users.logout') }}" style="border-radius: 5px;"><i class="bi bi-box-arrow-left pr-2"></i>Logout</a>               
                </div>
              </li>
          </div>
        </div>
      </div>
    </nav>
  </header>
{% endblock %}


{% block content %}
<div class="content-section">
    <div class="media mb-4">
        <img class="rounded-circle" src="{{ image_file }}" width="150" height="150">
        <div class="media-body">
          <h2 class="account-heading ml-2">{{ current_user.username }}</h2>             
          <p class="col text-secondary">{{ current_user.email }}</p>
          <p class="col text-secondary">Joined on {{ current_user.created.strftime("%B") + " " + current_user.created.strftime("%Y") }}</p>
          </div>
      </div>
      <div class="card p-3">
    <form method="POST" enctype="multipart/form-data">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Public Profile</legend>
            <div class="form-group">
                {{ form.hidden_tag() }}
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-md is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-md") }}
                {% endif %}
            </div>
            <div class="form-group">
              {{ form.phoneno.label(class="form-control-label") }}
              {% if form.phoneno.errors %}
                  {{ form.phoneno(class="form-control form-control-md is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.phoneno.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>  
              {% else %}
                  {{ form.phoneno(class="form-control form-control-md") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.address.label(class="form-control-label",id="phoneno") }}
              {% if form.address.errors %}
                  {{ form.address(class="form-control form-control-md is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.address.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>  
              {% else %}
                  {{ form.address(class="form-control form-control-md") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.picture.label() }}
              {{ form.picture(class="form-control-file") }}
              {% if form.picture.errors %}
                  {% for error in form.picture.errors %}
                      <span class="text-danger">{{ error }}</span></br>
                  {% endfor %}
              {% endif %}
            </div>
            <div class="form-group">
              <p class="mt-2"><em>Enter the data and get extra credits!</em></p>
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info submit") }}
        </div>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">  
</script>
{% endblock %}

mocktest/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <link rel = "icon" href = "../static/WA3.png" type = "image/x-icon"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.0/chart.js"></script>

    {% if title %}
        <title>Web Academy - {{ title }}</title>
    {% else %}
        <title>Web Academy</title>
    {% endif %}
</head>
<body>
  {% block header %}
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top mb-3">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Web Academy</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link active" href="{{ url_for('main.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}             
              <a class="nav-item nav-link" href="{{ url_for('tests.java') }}">Java</a>
              <a class="nav-item nav-link" href="{{ url_for('tests.python') }}">Python</a>                      
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle ml-3" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 0px;">
                  {% if current_user.image_file=='default.png' %}
                    {% if current_user.gender=='Male'%}
                      <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/male.png">
                    {% elif current_user.gender=='Female'%}
                      <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/female.png">
                    {% else %}
                      <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/other.png">
                    {% endif %}
                  {% else %}
                    <img class="rounded-circle" style="width:40px ;height:40px" src="../static/profile_pics/{{ image_file }}">
                  {% endif %}
                </a>
                <div class="dropdown-menu mt-2" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('users.account') }}"><i class="bi bi-person-lines-fill pr-2"></i>Account</a>
                  <a class="dropdown-item" href="{{ url_for('users.performance') }}"><i class="bi bi-graph-up pr-2"></i>Performance</a>
                  <a class="dropdown-item bg-danger text-white" href="{{ url_for('users.logout') }}" style="border-radius: 5px;"><i class="bi bi-box-arrow-left pr-2"></i>Logout</a>               
                </div>
              </li>            
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
  {% endblock %}
    <div class="container">
      <div class="flash_msg">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
        {% block content %}
        <div class="row">
          <div class="col">
            <h1 class="h1 ml-5">JAVA</h1>
            <p class="lead" style="font-weight: 500;">A programming language</p>
            <a href="{{ url_for('tests.java') }}" type="button" class="btn btn-outline-success ml-5 mb-4">Practice <i class="bi bi-caret-right-fill"></i></a>
          </div>
          <div class="col">
            <div class="card">
              <div class="card-header">
                <h3 class="h3" style="font-weight: 500;">Java Example:</h3>
              </div>
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <pre><span class="text-muted">// Your First Java Program</span>

<span class="text-danger">class</span> <span class="text-warning">HelloWorld</span> {
    <span class="text-danger">public static void</span> <span class="text-info">main</span>(String[] args) {
      <span class="text-secondary">System.out.println</span>(<span class="text-success">"Hello, World!"</span>); 
    }
}</pre>
                </blockquote>
              </div>
            </div>
          </div>
        </div>
        <br /><br /><br /><br />
        <div class="row">
          <div class="col">
            <div class="card mb-4">
              <div class="card-header">
                <h3 class="h3" style="font-weight: 500;">Python Example:</h3>
              </div>
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <pre><span class="text-muted"># Your First Python Program</span>

<span class="text-danger">print</span>(<span class="text-success">'Hello, world!'</span>)</pre>
                </blockquote>
              </div>
            </div>
          </div>
          <div class="col">
            <h1 class="h1 ml-4">PYTHON</h1>
            <p class="lead" style="font-weight: 500;">A programming language</p>
            <a href="{{ url_for('tests.python') }}" type="button" class="btn btn-outline-success ml-5 mb-5">Practice <i class="bi bi-caret-right-fill"></i></a>
          </div>
          </div>
        </div>
        {% endblock %}
    </div>  
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/mgalante/jquery.redirect/master/jquery.redirect.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
      var prevLink = document.referrer; 
      if(window.location.href == 'http://127.0.0.1:8080/' & (prevLink.includes('java-question') | prevLink.includes('python-question')) ){
        $('.flash_msg').append('<div class="alert alert-success alert-dismissible fade show" role="alert">Your attempt was successfully recorded!<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
      }
    </script>
    {% block script %}{% endblock %}
</body>
</html>
</html>

mocktest/templates/futureUseCode.html
{% extends 'base.html' %} {% block content %}
<div>{{ data }}</div>
{% endblock %}

mocktest/templates/java.html
{% extends 'base.html' %} {% block header %}
<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top mb-3">
		<div class="container">
			<a class="navbar-brand mr-4" href="/">Web Academy</a>
			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbarToggle"
				aria-controls="navbarToggle"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarToggle">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
				</div>
				<!-- Navbar Right Side -->
				<div class="navbar-nav">
					<a class="nav-item nav-link active" href="{{ url_for('tests.java') }}">Java</a>
					<a class="nav-item nav-link" href="{{ url_for('tests.python') }}">Python</a>
					<li class="nav-item dropdown">
						<a
							class="nav-link dropdown-toggle ml-3"
							href="#"
							id="navbarDropdownMenuLink"
							role="button"
							data-toggle="dropdown"
							aria-haspopup="true"
							aria-expanded="false"
							style="padding: 0px"
						>
							{% if current_user.image_file=='default.png' %} {% if
							current_user.gender=='Male'%}
							<img
								class="rounded-circle"
								style="width: 40px; height: 40px"
								src="../static/profile_pics/male.png"
							/>
							{% elif current_user.gender=='Female'%}
							<img
								class="rounded-circle"
								style="width: 40px; height: 40px"
								src="../static/profile_pics/female.png"
							/>
							{% else %}
							<img
								class="rounded-circle"
								style="width: 40px; height: 40px"
								src="../static/profile_pics/other.png"
							/>
							{% endif %} {% else %}
							<img
								class="rounded-circle"
								style="width: 40px; height: 40px"
								src="../static/profile_pics/{{ image_file }}"
							/>
							{% endif %}
						</a>
						<div class="dropdown-menu mt-2" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="{{ url_for('users.account') }}">
								<i class="bi bi-person-lines-fill pr-2"></i>Account
							</a>
							<a class="dropdown-item" href="{{ url_for('users.performance') }}">
								<i class="bi bi-graph-up pr-2"></i>Performance
							</a>
							<a
								class="dropdown-item bg-danger text-white"
								href="{{ url_for('users.logout') }}"
								style="border-radius: 5px"
							>
								<i class="bi bi-box-arrow-left pr-2"></i>Logout
							</a>
						</div>
					</li>
				</div>
			</div>
		</div>
	</nav>
</header>
{% endblock %} {% block content %}
<h2>Java Quiz</h2>
<p class="lead">You can test your Java skills with Web Academy Quiz.</p>
<ul class="list-group">
	<li class="list-group-item list-group-item-action">
		Data Types, Variables & Arrays
		<a
			href="{{ url_for('tests.question', module='Data_Types_Variables_Arrays', subject='java-question')}}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[0] }} Questions</span
		>
	</li>

	<li class="list-group-item list-group-item-action">
		Operators & Control Statements
		<a
			href="{{ url_for('tests.question', module='Operators_Control_Statements', subject='java-question') }}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[1] }} Questions</span
		>
	</li>

	<li class="list-group-item list-group-item-action">
		Classes & Methods
		<a
			href="{{ url_for('tests.question', module='Classes_Methods', subject='java-question') }}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[2] }} Questions</span
		>
	</li>

	<li class="list-group-item list-group-item-action">
		Exception
		<a
			href="{{ url_for('tests.question', module='Exception', subject='java-question') }}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[3] }} Questions</span
		>
	</li>

	<li class="list-group-item list-group-item-action">
		Inheritance
		<a
			href="{{ url_for('tests.question', module='Inheritance', subject='java-question') }}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[4] }} Questions</span
		>
	</li>

	<li class="list-group-item list-group-item-action">
		Threads
		<a
			href="{{ url_for('tests.question', module='Threads', subject='java-question') }}"
			class="float-right btn btn-outline-success"
		>
			Take a test
			<i class="bi bi-journals ml-1"></i>
		</a>
		<span class="mr-3 mt-1 p-2 float-right badge badge-primary badge-pill"
			>{{ module[5] }} Questions</span
		>
	</li>
</ul>

<p class="text-danger mt-5 font-weight-bold">
	Note:
	<span class="text-secondary"
		>Once you click on
		<span class="badge badge-pill badge-success">Take a test </span>
		a timer of
		<span class="badge badge-pill badge-danger">30 Minutes </span>
		will automatically begin. Once the timer is over the question paper will be
		submitted with the answers marked. Each MCQ carries
		<span class="badge badge-pill badge-info">2 Marks </span>
		for a total of
		<span class="badge badge-pill badge-info">40 Marks </span>
		containing
		<span class="badge badge-pill badge-info">20 Random Questions </span>.
	</span>
</p>

{% endblock %} {% block script %}
<script></script>
{% endblock %}

mocktest/templates/login.html
{% extends "base.html" %} {% block header %}
<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top mb-3">
		<div class="container">
			<a class="navbar-brand mr-4" href="/">Web Academy</a>
			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbarToggle"
				aria-controls="navbarToggle"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarToggle">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
				</div>
				<!-- Navbar Right Side -->
				<div class="navbar-nav">
					<a class="nav-item nav-link active" href="{{ url_for('users.login') }}"
						>Login</a
					>
					<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
				</div>
			</div>
		</div>
	</nav>
</header>
{% endblock %} {% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Log In</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{
				form.email(class="form-control form-control-md is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %} {{ form.email(class="form-control form-control-md") }} {% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }} {% if form.password.errors
				%} {{ form.password(class="form-control form-control-md is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %} {{ form.password(class="form-control form-control-md") }} {% endif %}
			</div>
			<div class="form-check">
				{{ form.remember(class="form-check-input") }} {{
				form.remember.label(class="form-check-label") }}
			</div>
		</fieldset>
		<div class="form-group">{{ form.submit(class="btn btn-outline-info") }}</div>
		<small class="text-muted ml-2">
			<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
		</small>
	</form>
</div>
<div class="border-top pt-3">
	<small class="text-muted">
		Need An Account?
		<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
	</small>
</div>
{% endblock content %}